name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run install script
      run: ./install_wp.sh --install

    - name: Backup
      run: ./backup_wp.sh --backup

        #- name: Restore
        #  run: ./install_wp.sh --restore ""
      #    - name: Super-Linter
      #uses: github/super-linter@v2.1.0
